"""initial migration

Revision ID: 16c8298d3854
Revises: 
Create Date: 2024-03-02 16:02:09.598995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c8298d3854'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trophy_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psn_username', sa.String(length=255), nullable=False),
    sa.Column('game_id', sa.String(length=255), nullable=False),
    sa.Column('game_name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.Column('trophies_version', sa.Float(precision=2), nullable=False),
    sa.Column('game_icon_url', sa.String(length=255), nullable=True),
    sa.Column('has_extra_trophies', sa.Boolean(), nullable=True),
    sa.Column('earned_silver', sa.Integer(), nullable=True),
    sa.Column('earned_bronze', sa.Integer(), nullable=True),
    sa.Column('earned_gold', sa.Integer(), nullable=True),
    sa.Column('earned_platinum', sa.Integer(), nullable=True),
    sa.Column('total_silver', sa.Integer(), nullable=True),
    sa.Column('total_bronze', sa.Integer(), nullable=True),
    sa.Column('total_gold', sa.Integer(), nullable=True),
    sa.Column('total_platinum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trophy_titles')
    # ### end Alembic commands ###
